table 'Brickset URL Lookup'
	lineageTag: b673bc92-0d0a-41d5-9990-8840b748ab51

	column 'Brickset URL ID'
		dataType: int64
		formatString: 0
		lineageTag: e437353b-a17c-4bc2-9f4d-e93c70385244
		summarizeBy: none
		sourceColumn: Brickset URL ID

		annotation SummarizationSetBy = Automatic

	column bricksetURL
		dataType: string
		lineageTag: 45d7a55c-bb97-4d20-ac56-56ccfe076b79
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: bricksetURL

		annotation SummarizationSetBy = Automatic

	partition 'Brickset URL Lookup' = m
		mode: import
		source =
				let
				    Source = lego_sets_source,
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"set_id", type text}, {"name", type text}, {"year", Int64.Type}, {"theme", type text}, {"subtheme", type text}, {"themeGroup", type text}, {"category", type text}, {"pieces", Int64.Type}, {"minifigs", type text}, {"agerange_min", type text}, {"US_retailPrice", type text}, {"bricksetURL", type text}, {"thumbnailURL", type text}, {"imageURL", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","","No SubTheme",Replacer.ReplaceValue,{"subtheme"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"bricksetURL"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "bricksetURL"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Brickset URL ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

