table 'Category Lookup'
	lineageTag: 75673d89-9a27-4283-b8d3-3759b86f0900

	column 'Category ID'
		dataType: int64
		formatString: 0
		lineageTag: c743b6a2-f741-4841-ba08-aebfbf72af62
		summarizeBy: none
		sourceColumn: Category ID

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 1b750a6d-97dc-4570-a320-e29396bc9bc0
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition 'Category Lookup' = m
		mode: import
		source =
				let
				    Source = lego_sets_source,
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"set_id", type text}, {"name", type text}, {"year", Int64.Type}, {"theme", type text}, {"subtheme", type text}, {"themeGroup", type text}, {"category", type text}, {"pieces", Int64.Type}, {"minifigs", type text}, {"agerange_min", type text}, {"US_retailPrice", type text}, {"bricksetURL", type text}, {"thumbnailURL", type text}, {"imageURL", type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","","No SubTheme",Replacer.ReplaceValue,{"subtheme"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"category"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "category"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Category ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

