table 'Theme Lookup'
	lineageTag: 7ccdda0a-6ef2-4dc0-9166-065dce5e53d9

	column 'Theme ID'
		dataType: int64
		formatString: 0
		lineageTag: c3f5e69b-7f61-4146-bfc2-c4428f26b818
		summarizeBy: none
		sourceColumn: Theme ID

		annotation SummarizationSetBy = Automatic

	column theme
		dataType: string
		lineageTag: 539d468d-c90a-4837-a5eb-bd5dca71b360
		summarizeBy: none
		sourceColumn: theme

		annotation SummarizationSetBy = Automatic

	partition 'Theme Lookup' = m
		mode: import
		source =
				let
				    Source = lego_sets_source,
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"set_id", type text}, {"name", type text}, {"year", Int64.Type}, {"theme", type text}, {"subtheme", type text}, {"themeGroup", type text}, {"category", type text}, {"pieces", Int64.Type}, {"minifigs", type text}, {"agerange_min", type text}, {"US_retailPrice", type text}, {"bricksetURL", type text}, {"thumbnailURL", type text}, {"imageURL", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"theme"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "theme"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"Index", "Theme ID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

