table 'Thumbnail URL Lookup'
	lineageTag: aad4324d-77f9-4582-aea5-999a8b4e23a1

	column 'Thumbnail URL ID'
		dataType: int64
		formatString: 0
		lineageTag: 245a97b2-0c25-4083-9509-c369a9ac4fa8
		summarizeBy: none
		sourceColumn: Thumbnail URL ID

		annotation SummarizationSetBy = Automatic

	column thumbnailURL
		dataType: string
		lineageTag: 00600022-f301-4036-9c92-ac4b8dbe53c4
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: thumbnailURL

		annotation SummarizationSetBy = Automatic

	partition 'Thumbnail URL Lookup' = m
		mode: import
		source =
				let
				    Source = lego_sets_source,
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"set_id", type text}, {"name", type text}, {"year", Int64.Type}, {"theme", type text}, {"subtheme", type text}, {"themeGroup", type text}, {"category", type text}, {"pieces", Int64.Type}, {"minifigs", type text}, {"agerange_min", type text}, {"US_retailPrice", type text}, {"bricksetURL", type text}, {"thumbnailURL", type text}, {"imageURL", type text}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"thumbnailURL"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Other Columns", "New thumbnailURL", each if [thumbnailURL] = "" then "https://photos.onedrive.com/share/EFCFA07183130BE2!1319829?cid=EFCFA07183130BE2&resId=EFCFA07183130BE2!1319829&authkey=!AFe3fNDMvNCrNvE&ithint=photo&e=8JglZh" else [thumbnailURL]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"New thumbnailURL", type text}}),
				    #"Removed Columns4" = Table.RemoveColumns(#"Changed Type1",{"thumbnailURL"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns4",{{"New thumbnailURL", "thumbnailURL"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns4" = Table.ReorderColumns(#"Added Index",{"Index", "thumbnailURL"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns4",{{"Index", "Thumbnail URL ID"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

